// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyStorage.proto

package com.smartcity.energystorage;

public final class EnergyStorageProto {
  private EnergyStorageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energystorage_StoreEnergyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energystorage_StoreEnergyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energystorage_StoreEnergyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energystorage_StoreEnergyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023EnergyStorage.proto\022\renergystorage\"*\n\022" +
      "StoreEnergyRequest\022\024\n\014energyAmount\030\001 \001(\001" +
      "\"&\n\023StoreEnergyResponse\022\017\n\007success\030\001 \001(\010" +
      "2g\n\rEnergyStorage\022V\n\013storeEnergy\022!.energ" +
      "ystorage.StoreEnergyRequest\032\".energystor" +
      "age.StoreEnergyResponse\"\000B3\n\033com.smartci" +
      "ty.energystorageB\022EnergyStorageProtoP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_energystorage_StoreEnergyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_energystorage_StoreEnergyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energystorage_StoreEnergyRequest_descriptor,
        new java.lang.String[] { "EnergyAmount", });
    internal_static_energystorage_StoreEnergyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_energystorage_StoreEnergyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energystorage_StoreEnergyResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
