// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyStorage.proto

package com.smartcity.energystorage;

public interface StoreEnergyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energystorage.StoreEnergyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double energyAmount = 1;</code>
   */
  double getEnergyAmount();
}
