// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyStorage.proto

package com.smartcity.energystorage;

public interface StoreEnergyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energystorage.StoreEnergyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
