// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyConsumption.proto

package com.smartcity.energyconsumption;

public interface ConsumeEnergyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyconsumption.ConsumeEnergyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double energyAmount = 1;</code>
   */
  double getEnergyAmount();
}
