// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyConsumption.proto

package com.smartcity.energyconsumption;

public interface ConsumeEnergyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:energyconsumption.ConsumeEnergyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
