// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyConsumption.proto

package com.smartcity.energyconsumption;

public final class EnergyConsumptionProto {
  private EnergyConsumptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyconsumption_ConsumeEnergyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyconsumption_ConsumeEnergyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_energyconsumption_ConsumeEnergyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_energyconsumption_ConsumeEnergyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027EnergyConsumption.proto\022\021energyconsump" +
      "tion\",\n\024ConsumeEnergyRequest\022\024\n\014energyAm" +
      "ount\030\001 \001(\001\"(\n\025ConsumeEnergyResponse\022\017\n\007s" +
      "uccess\030\001 \001(\0102y\n\021EnergyConsumption\022d\n\rcon" +
      "sumeEnergy\022\'.energyconsumption.ConsumeEn" +
      "ergyRequest\032(.energyconsumption.ConsumeE" +
      "nergyResponse\"\000B;\n\037com.smartcity.energyc" +
      "onsumptionB\026EnergyConsumptionProtoP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_energyconsumption_ConsumeEnergyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_energyconsumption_ConsumeEnergyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyconsumption_ConsumeEnergyRequest_descriptor,
        new java.lang.String[] { "EnergyAmount", });
    internal_static_energyconsumption_ConsumeEnergyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_energyconsumption_ConsumeEnergyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_energyconsumption_ConsumeEnergyResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
