// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WindTurbine.proto

package com.smartcity.windturbines;

public interface GenerateEnergyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:windturbines.GenerateEnergyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double energyGenerated = 1;</code>
   */
  double getEnergyGenerated();
}
