// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WindTurbine.proto

package com.smartcity.windturbines;

public interface GenerateEnergyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:windturbines.GenerateEnergyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double windSpeed = 1;</code>
   */
  double getWindSpeed();
}
