// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SolarPanel.proto

package com.smartcity.solarpanels;

public interface GenerateEnergyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solarpanels.GenerateEnergyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double sunExposure = 1;</code>
   */
  double getSunExposure();
}
