// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SolarPanel.proto

package com.smartcity.solarpanels;

/**
 * Protobuf type {@code solarpanels.GenerateEnergyResponse}
 */
public  final class GenerateEnergyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solarpanels.GenerateEnergyResponse)
    GenerateEnergyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateEnergyResponse.newBuilder() to construct.
  private GenerateEnergyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateEnergyResponse() {
    energyGenerated_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GenerateEnergyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            energyGenerated_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartcity.solarpanels.SolarPanelsProto.internal_static_solarpanels_GenerateEnergyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartcity.solarpanels.SolarPanelsProto.internal_static_solarpanels_GenerateEnergyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartcity.solarpanels.GenerateEnergyResponse.class, com.smartcity.solarpanels.GenerateEnergyResponse.Builder.class);
  }

  public static final int ENERGYGENERATED_FIELD_NUMBER = 1;
  private double energyGenerated_;
  /**
   * <code>double energyGenerated = 1;</code>
   */
  public double getEnergyGenerated() {
    return energyGenerated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (energyGenerated_ != 0D) {
      output.writeDouble(1, energyGenerated_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (energyGenerated_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, energyGenerated_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartcity.solarpanels.GenerateEnergyResponse)) {
      return super.equals(obj);
    }
    com.smartcity.solarpanels.GenerateEnergyResponse other = (com.smartcity.solarpanels.GenerateEnergyResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getEnergyGenerated())
        == java.lang.Double.doubleToLongBits(
            other.getEnergyGenerated()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENERGYGENERATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEnergyGenerated()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartcity.solarpanels.GenerateEnergyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartcity.solarpanels.GenerateEnergyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code solarpanels.GenerateEnergyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solarpanels.GenerateEnergyResponse)
      com.smartcity.solarpanels.GenerateEnergyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartcity.solarpanels.SolarPanelsProto.internal_static_solarpanels_GenerateEnergyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartcity.solarpanels.SolarPanelsProto.internal_static_solarpanels_GenerateEnergyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartcity.solarpanels.GenerateEnergyResponse.class, com.smartcity.solarpanels.GenerateEnergyResponse.Builder.class);
    }

    // Construct using com.smartcity.solarpanels.GenerateEnergyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      energyGenerated_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartcity.solarpanels.SolarPanelsProto.internal_static_solarpanels_GenerateEnergyResponse_descriptor;
    }

    @java.lang.Override
    public com.smartcity.solarpanels.GenerateEnergyResponse getDefaultInstanceForType() {
      return com.smartcity.solarpanels.GenerateEnergyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartcity.solarpanels.GenerateEnergyResponse build() {
      com.smartcity.solarpanels.GenerateEnergyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartcity.solarpanels.GenerateEnergyResponse buildPartial() {
      com.smartcity.solarpanels.GenerateEnergyResponse result = new com.smartcity.solarpanels.GenerateEnergyResponse(this);
      result.energyGenerated_ = energyGenerated_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartcity.solarpanels.GenerateEnergyResponse) {
        return mergeFrom((com.smartcity.solarpanels.GenerateEnergyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartcity.solarpanels.GenerateEnergyResponse other) {
      if (other == com.smartcity.solarpanels.GenerateEnergyResponse.getDefaultInstance()) return this;
      if (other.getEnergyGenerated() != 0D) {
        setEnergyGenerated(other.getEnergyGenerated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartcity.solarpanels.GenerateEnergyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartcity.solarpanels.GenerateEnergyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double energyGenerated_ ;
    /**
     * <code>double energyGenerated = 1;</code>
     */
    public double getEnergyGenerated() {
      return energyGenerated_;
    }
    /**
     * <code>double energyGenerated = 1;</code>
     */
    public Builder setEnergyGenerated(double value) {
      
      energyGenerated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double energyGenerated = 1;</code>
     */
    public Builder clearEnergyGenerated() {
      
      energyGenerated_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solarpanels.GenerateEnergyResponse)
  }

  // @@protoc_insertion_point(class_scope:solarpanels.GenerateEnergyResponse)
  private static final com.smartcity.solarpanels.GenerateEnergyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartcity.solarpanels.GenerateEnergyResponse();
  }

  public static com.smartcity.solarpanels.GenerateEnergyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateEnergyResponse>
      PARSER = new com.google.protobuf.AbstractParser<GenerateEnergyResponse>() {
    @java.lang.Override
    public GenerateEnergyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GenerateEnergyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenerateEnergyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateEnergyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartcity.solarpanels.GenerateEnergyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

