// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SolarPanel.proto

package com.smartcity.solarpanels;

public interface GenerateEnergyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solarpanels.GenerateEnergyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double energyGenerated = 1;</code>
   */
  double getEnergyGenerated();
}
