// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SolarPanel.proto

package com.smartcity.solarpanels;

public final class SolarPanelsProto {
  private SolarPanelsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solarpanels_GenerateEnergyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solarpanels_GenerateEnergyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solarpanels_GenerateEnergyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solarpanels_GenerateEnergyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SolarPanel.proto\022\013solarpanels\",\n\025Gener" +
      "ateEnergyRequest\022\023\n\013sunExposure\030\001 \001(\001\"1\n" +
      "\026GenerateEnergyResponse\022\027\n\017energyGenerat" +
      "ed\030\001 \001(\0012j\n\013SolarPanels\022[\n\016generateEnerg" +
      "y\022\".solarpanels.GenerateEnergyRequest\032#." +
      "solarpanels.GenerateEnergyResponse\"\000B/\n\031" +
      "com.smartcity.solarpanelsB\020SolarPanelsPr" +
      "otoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_solarpanels_GenerateEnergyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_solarpanels_GenerateEnergyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solarpanels_GenerateEnergyRequest_descriptor,
        new java.lang.String[] { "SunExposure", });
    internal_static_solarpanels_GenerateEnergyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_solarpanels_GenerateEnergyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solarpanels_GenerateEnergyResponse_descriptor,
        new java.lang.String[] { "EnergyGenerated", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
